//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.iac {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.iac.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Tarea.
        /// </summary>
        internal static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular:.
        /// </summary>
        internal static string celular {
            get {
                return ResourceManager.GetString("celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular.
        /// </summary>
        internal static string celular2 {
            get {
                return ResourceManager.GetString("celular2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colaboradores.
        /// </summary>
        internal static string colaboradores {
            get {
                return ResourceManager.GetString("colaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico:.
        /// </summary>
        internal static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        internal static string correo2 {
            get {
                return ResourceManager.GetString("correo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Colaboradores.
        /// </summary>
        internal static string datoscolaboradores {
            get {
                return ResourceManager.GetString("datoscolaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos IAC.
        /// </summary>
        internal static string datosiac {
            get {
                return ResourceManager.GetString("datosiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Institución.
        /// </summary>
        internal static string datosins {
            get {
                return ResourceManager.GetString("datosins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento o sede:.
        /// </summary>
        internal static string departamento {
            get {
                return ResourceManager.GetString("departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento o sede.
        /// </summary>
        internal static string departamento2 {
            get {
                return ResourceManager.GetString("departamento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        internal static string descargar {
            get {
                return ResourceManager.GetString("descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        internal static string direccion {
            get {
                return ResourceManager.GetString("direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string direccion2 {
            get {
                return ResourceManager.GetString("direccion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección IAC:.
        /// </summary>
        internal static string direccioniac {
            get {
                return ResourceManager.GetString("direccioniac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección IAC.
        /// </summary>
        internal static string direccioniac2 {
            get {
                return ResourceManager.GetString("direccioniac2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string eleminar {
            get {
                return ResourceManager.GetString("eleminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado:.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string estado2 {
            get {
                return ResourceManager.GetString("estado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Ingreso:.
        /// </summary>
        internal static string fechaingreso {
            get {
                return ResourceManager.GetString("fechaingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Ingreso.
        /// </summary>
        internal static string fechaingreso2 {
            get {
                return ResourceManager.GetString("fechaingreso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Nacimiento:.
        /// </summary>
        internal static string fechanacimiento {
            get {
                return ResourceManager.GetString("fechanacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Nacimiento.
        /// </summary>
        internal static string fechanacimiento2 {
            get {
                return ResourceManager.GetString("fechanacimiento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos:.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotografía:.
        /// </summary>
        internal static string fotografia {
            get {
                return ResourceManager.GetString("fotografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información IAC.
        /// </summary>
        internal static string informacion {
            get {
                return ResourceManager.GetString("informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo Departamento.
        /// </summary>
        internal static string logodepart {
            get {
                return ResourceManager.GetString("logodepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo Institución.
        /// </summary>
        internal static string logoinstitucion {
            get {
                return ResourceManager.GetString("logoinstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombre2 {
            get {
                return ResourceManager.GetString("nombre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo:.
        /// </summary>
        internal static string nombrecompleto {
            get {
                return ResourceManager.GetString("nombrecompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo.
        /// </summary>
        internal static string nombrecompleto2 {
            get {
                return ResourceManager.GetString("nombrecompleto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre IAC:.
        /// </summary>
        internal static string nombreiac {
            get {
                return ResourceManager.GetString("nombreiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre IAC.
        /// </summary>
        internal static string nombreiac2 {
            get {
                return ResourceManager.GetString("nombreiac2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Representante:.
        /// </summary>
        internal static string nombrerepre {
            get {
                return ResourceManager.GetString("nombrerepre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Identificación:.
        /// </summary>
        internal static string numeroid {
            get {
                return ResourceManager.GetString("numeroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Identificación.
        /// </summary>
        internal static string numeroid2 {
            get {
                return ResourceManager.GetString("numeroid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País:.
        /// </summary>
        internal static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto:.
        /// </summary>
        internal static string puesto {
            get {
                return ResourceManager.GetString("puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo:.
        /// </summary>
        internal static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string subir {
            get {
                return ResourceManager.GetString("subir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea que desempeña:.
        /// </summary>
        internal static string tareaquedesempena {
            get {
                return ResourceManager.GetString("tareaquedesempena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea que desempeña.
        /// </summary>
        internal static string tareaquedesempena2 {
            get {
                return ResourceManager.GetString("tareaquedesempena2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas que desempeña:.
        /// </summary>
        internal static string tareasdesempena {
            get {
                return ResourceManager.GetString("tareasdesempena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono:.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono 1.
        /// </summary>
        internal static string telefono1 {
            get {
                return ResourceManager.GetString("telefono1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono 2.
        /// </summary>
        internal static string telefono2 {
            get {
                return ResourceManager.GetString("telefono2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono 3.
        /// </summary>
        internal static string telefono3 {
            get {
                return ResourceManager.GetString("telefono3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string telefono4 {
            get {
                return ResourceManager.GetString("telefono4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Institución:.
        /// </summary>
        internal static string telefonoinstitucion {
            get {
                return ResourceManager.GetString("telefonoinstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Institución.
        /// </summary>
        internal static string telefonoinstitucion2 {
            get {
                return ResourceManager.GetString("telefonoinstitucion2", resourceCulture);
            }
        }
    }
}
