//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.index {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.index.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abril.
        /// </summary>
        internal static string Abril {
            get {
                return ResourceManager.GetString("Abril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agosto.
        /// </summary>
        internal static string Agosto {
            get {
                return ResourceManager.GetString("Agosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día.
        /// </summary>
        internal static string dia {
            get {
                return ResourceManager.GetString("dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días.
        /// </summary>
        internal static string dias {
            get {
                return ResourceManager.GetString("dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diciembre.
        /// </summary>
        internal static string Diciembre {
            get {
                return ResourceManager.GetString("Diciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enero.
        /// </summary>
        internal static string Enero {
            get {
                return ResourceManager.GetString("Enero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos Terminados.
        /// </summary>
        internal static string eventos1 {
            get {
                return ResourceManager.GetString("eventos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Próximos Eventos.
        /// </summary>
        internal static string eventos2 {
            get {
                return ResourceManager.GetString("eventos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Febrero.
        /// </summary>
        internal static string Febrero {
            get {
                return ResourceManager.GetString("Febrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finaliza en.
        /// </summary>
        internal static string finaliza {
            get {
                return ResourceManager.GetString("finaliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy.
        /// </summary>
        internal static string hoy {
            get {
                return ResourceManager.GetString("hoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Julio.
        /// </summary>
        internal static string Julio {
            get {
                return ResourceManager.GetString("Julio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Junio.
        /// </summary>
        internal static string Junio {
            get {
                return ResourceManager.GetString("Junio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero.
        /// </summary>
        internal static string labelBoard {
            get {
                return ResourceManager.GetString("labelBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marzo.
        /// </summary>
        internal static string Marzo {
            get {
                return ResourceManager.GetString("Marzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayo.
        /// </summary>
        internal static string Mayo {
            get {
                return ResourceManager.GetString("Mayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas Uso de Espacios.
        /// </summary>
        internal static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noviembre.
        /// </summary>
        internal static string Noviembre {
            get {
                return ResourceManager.GetString("Noviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Octubre.
        /// </summary>
        internal static string Octubre {
            get {
                return ResourceManager.GetString("Octubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Septiembre.
        /// </summary>
        internal static string Septiembre {
            get {
                return ResourceManager.GetString("Septiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos por Terminar.
        /// </summary>
        internal static string terminate {
            get {
                return ResourceManager.GetString("terminate", resourceCulture);
            }
        }
    }
}
