//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Mensajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mensajes.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión a la base de datos.
        /// </summary>
        internal static string baseDatosError {
            get {
                return ResourceManager.GetString("baseDatosError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión a la base de datos añadida Correctamente.
        /// </summary>
        internal static string cnxString {
            get {
                return ResourceManager.GetString("cnxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar datos.
        /// </summary>
        internal static string consultarError {
            get {
                return ResourceManager.GetString("consultarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario por defecto a sido creado, por favor intente de nuevo con los datos del usuario por defecto.
        /// </summary>
        internal static string defaultUser {
            get {
                return ResourceManager.GetString("defaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   eliminado Correctamente.
        /// </summary>
        internal static string EliminadoCorrecto {
            get {
                return ResourceManager.GetString("EliminadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al  eliminar el Registro.
        /// </summary>
        internal static string eliminarError {
            get {
                return ResourceManager.GetString("eliminarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        internal static string exito {
            get {
                return ResourceManager.GetString("exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor revise la extensión del archivo antes de continuar.
        /// </summary>
        internal static string extError {
            get {
                return ResourceManager.GetString("extError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor complete todos los campos antes de continuar.
        /// </summary>
        internal static string fillAll {
            get {
                return ResourceManager.GetString("fillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  guardado correctamente.
        /// </summary>
        internal static string GuardadoCorrecto {
            get {
                return ResourceManager.GetString("GuardadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado Correctamente.
        /// </summary>
        internal static string guardarCorrecto {
            get {
                return ResourceManager.GetString("guardarCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el Registro.
        /// </summary>
        internal static string guardarError {
            get {
                return ResourceManager.GetString("guardarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicialización de la base de datos ejecutado correctamente.
        /// </summary>
        internal static string initialScript {
            get {
                return ResourceManager.GetString("initialScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al inicializar la base de datos.
        /// </summary>
        internal static string initialScriptError {
            get {
                return ResourceManager.GetString("initialScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respaldo creado correctamente.
        /// </summary>
        internal static string restaurar {
            get {
                return ResourceManager.GetString("restaurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al restaurar el respaldo.
        /// </summary>
        internal static string restaurarError {
            get {
                return ResourceManager.GetString("restaurarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor cargue un archivo antes de continuar.
        /// </summary>
        internal static string selectFile {
            get {
                return ResourceManager.GetString("selectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione un registro antes de continuar.
        /// </summary>
        internal static string selectOne {
            get {
                return ResourceManager.GetString("selectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al subir el Archivo.
        /// </summary>
        internal static string subirArchivo {
            get {
                return ResourceManager.GetString("subirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a son tipo de archivos validos, por favor intente de nuevo.
        /// </summary>
        internal static string tipoArchivo {
            get {
                return ResourceManager.GetString("tipoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor suba un archivo antes de continuar.
        /// </summary>
        internal static string uploadFile {
            get {
                return ResourceManager.GetString("uploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no Existe, por favor revise su usuario y contraseña e intente de nuevo.
        /// </summary>
        internal static string UserNoExiste {
            get {
                return ResourceManager.GetString("UserNoExiste", resourceCulture);
            }
        }
    }
}
