//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.reporte {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.reporte.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        internal static string anno {
            get {
                return ResourceManager.GetString("anno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abril.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agosto.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        internal static string cantidad_participantes {
            get {
                return ResourceManager.GetString("cantidad_participantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condición.
        /// </summary>
        internal static string condicion {
            get {
                return ResourceManager.GetString("condicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Reporte.
        /// </summary>
        internal static string consultar {
            get {
                return ResourceManager.GetString("consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo Equipo.
        /// </summary>
        internal static string costoEquipo {
            get {
                return ResourceManager.GetString("costoEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diciembre.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encargado.
        /// </summary>
        internal static string Encargado {
            get {
                return ResourceManager.GetString("Encargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio.
        /// </summary>
        internal static string Espacio {
            get {
                return ResourceManager.GetString("Espacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evento.
        /// </summary>
        internal static string evento {
            get {
                return ResourceManager.GetString("evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Febrero.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Evento.
        /// </summary>
        internal static string fechaEvento {
            get {
                return ResourceManager.GetString("fechaEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string fecha_EventoDiario {
            get {
                return ResourceManager.GetString("fecha_EventoDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final.
        /// </summary>
        internal static string fecha_Final {
            get {
                return ResourceManager.GetString("fecha_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        internal static string fecha_Inicio {
            get {
                return ResourceManager.GetString("fecha_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hombres.
        /// </summary>
        internal static string Hombres {
            get {
                return ResourceManager.GetString("Hombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Final.
        /// </summary>
        internal static string hora_final {
            get {
                return ResourceManager.GetString("hora_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Inicio.
        /// </summary>
        internal static string hora_inicio {
            get {
                return ResourceManager.GetString("hora_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string idEquipo {
            get {
                return ResourceManager.GetString("idEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string imprimir {
            get {
                return ResourceManager.GetString("imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enero.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Julio.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Junio.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        internal static string marca {
            get {
                return ResourceManager.GetString("marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marzo.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayo.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        internal static string mes {
            get {
                return ResourceManager.GetString("mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        internal static string modelo {
            get {
                return ResourceManager.GetString("modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mujeres.
        /// </summary>
        internal static string Mujeres {
            get {
                return ResourceManager.GetString("Mujeres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encargado.
        /// </summary>
        internal static string nombre_Completo {
            get {
                return ResourceManager.GetString("nombre_Completo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evento.
        /// </summary>
        internal static string nombre_Evento {
            get {
                return ResourceManager.GetString("nombre_Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Institución.
        /// </summary>
        internal static string nombre_institucion {
            get {
                return ResourceManager.GetString("nombre_institucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noviembre.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string observaciones {
            get {
                return ResourceManager.GetString("observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Octubre.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo.
        /// </summary>
        internal static string periodo {
            get {
                return ResourceManager.GetString("periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Placa.
        /// </summary>
        internal static string placa {
            get {
                return ResourceManager.GetString("placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promedio.
        /// </summary>
        internal static string promedio {
            get {
                return ResourceManager.GetString("promedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Septiembre.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie.
        /// </summary>
        internal static string serie {
            get {
                return ResourceManager.GetString("serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        internal static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Equipo.
        /// </summary>
        internal static string tipoEquipo {
            get {
                return ResourceManager.GetString("tipoEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Evento.
        /// </summary>
        internal static string tipoEvento {
            get {
                return ResourceManager.GetString("tipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Todas --.
        /// </summary>
        internal static string todasCondicion {
            get {
                return ResourceManager.GetString("todasCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Todo --.
        /// </summary>
        internal static string todos {
            get {
                return ResourceManager.GetString("todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
