//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.seguridad {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.seguridad.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistencia.
        /// </summary>
        internal static string asistencia {
            get {
                return ResourceManager.GetString("asistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respaldar / Restaurar.
        /// </summary>
        internal static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitácora.
        /// </summary>
        internal static string bitacora {
            get {
                return ResourceManager.GetString("bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condición.
        /// </summary>
        internal static string chkcondicion {
            get {
                return ResourceManager.GetString("chkcondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupación.
        /// </summary>
        internal static string chkOcupacion {
            get {
                return ResourceManager.GetString("chkOcupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo.
        /// </summary>
        internal static string chkPeriodo {
            get {
                return ResourceManager.GetString("chkPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona.
        /// </summary>
        internal static string chkPersona {
            get {
                return ResourceManager.GetString("chkPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Evento.
        /// </summary>
        internal static string chkTipoEvento {
            get {
                return ResourceManager.GetString("chkTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Persona.
        /// </summary>
        internal static string chkTipoPersona {
            get {
                return ResourceManager.GetString("chkTipoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código:.
        /// </summary>
        internal static string codigo2 {
            get {
                return ResourceManager.GetString("codigo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Colaboradores.
        /// </summary>
        internal static string datoscolaboradores {
            get {
                return ResourceManager.GetString("datoscolaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos IAC.
        /// </summary>
        internal static string datosiac {
            get {
                return ResourceManager.GetString("datosiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Institución.
        /// </summary>
        internal static string datosins {
            get {
                return ResourceManager.GetString("datosins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un Valor.
        /// </summary>
        internal static string ddlSelect {
            get {
                return ResourceManager.GetString("ddlSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        internal static string descargar {
            get {
                return ResourceManager.GetString("descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string descripcion2 {
            get {
                return ResourceManager.GetString("descripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo.
        /// </summary>
        internal static string equipo {
            get {
                return ResourceManager.GetString("equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio.
        /// </summary>
        internal static string espacio {
            get {
                return ResourceManager.GetString("espacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por Favor Espere....
        /// </summary>
        internal static string espere {
            get {
                return ResourceManager.GetString("espere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadística.
        /// </summary>
        internal static string estadistica {
            get {
                return ResourceManager.GetString("estadistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        internal static string estudiante {
            get {
                return ResourceManager.GetString("estudiante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos.
        /// </summary>
        internal static string eventos {
            get {
                return ResourceManager.GetString("eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos Diarios.
        /// </summary>
        internal static string eventosdiarios {
            get {
                return ResourceManager.GetString("eventosdiarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string fecha_Accion {
            get {
                return ResourceManager.GetString("fecha_Accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        internal static string hora_Accion {
            get {
                return ResourceManager.GetString("hora_Accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción.
        /// </summary>
        internal static string inscripcion {
            get {
                return ResourceManager.GetString("inscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instituciones.
        /// </summary>
        internal static string instituciones {
            get {
                return ResourceManager.GetString("instituciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventario.
        /// </summary>
        internal static string inventario {
            get {
                return ResourceManager.GetString("inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Matricula.
        /// </summary>
        internal static string listaMatricula {
            get {
                return ResourceManager.GetString("listaMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Respaldos.
        /// </summary>
        internal static string listaRespaldo {
            get {
                return ResourceManager.GetString("listaRespaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcas.
        /// </summary>
        internal static string marcas {
            get {
                return ResourceManager.GetString("marcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string modificar {
            get {
                return ResourceManager.GetString("modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulo.
        /// </summary>
        internal static string modulo_Accesado {
            get {
                return ResourceManager.GetString("modulo_Accesado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimiento.
        /// </summary>
        internal static string movimiento_Ejecutado {
            get {
                return ResourceManager.GetString("movimiento_Ejecutado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevos Valores.
        /// </summary>
        internal static string newValues {
            get {
                return ResourceManager.GetString("newValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo.
        /// </summary>
        internal static string nombrecompleto {
            get {
                return ResourceManager.GetString("nombrecompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo:.
        /// </summary>
        internal static string nombrecompleto2 {
            get {
                return ResourceManager.GetString("nombrecompleto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Identificación.
        /// </summary>
        internal static string numerodeid {
            get {
                return ResourceManager.GetString("numerodeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Identificación:.
        /// </summary>
        internal static string numerodeid2 {
            get {
                return ResourceManager.GetString("numerodeid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Identificación.
        /// </summary>
        internal static string numero_Identificacion {
            get {
                return ResourceManager.GetString("numero_Identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valores Anteriores.
        /// </summary>
        internal static string oldValues {
            get {
                return ResourceManager.GetString("oldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página IAC:.
        /// </summary>
        internal static string paginaiac {
            get {
                return ResourceManager.GetString("paginaiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Mantenimiento:.
        /// </summary>
        internal static string paginaman {
            get {
                return ResourceManager.GetString("paginaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Proceso:.
        /// </summary>
        internal static string paginapro {
            get {
                return ResourceManager.GetString("paginapro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Seguridad:.
        /// </summary>
        internal static string paginaseg {
            get {
                return ResourceManager.GetString("paginaseg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        internal static string participantes {
            get {
                return ResourceManager.GetString("participantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        internal static string permisos {
            get {
                return ResourceManager.GetString("permisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        internal static string principal {
            get {
                return ResourceManager.GetString("principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        internal static string puesto {
            get {
                return ResourceManager.GetString("puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string reportes {
            get {
                return ResourceManager.GetString("reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Respaldo.
        /// </summary>
        internal static string respaldar {
            get {
                return ResourceManager.GetString("respaldar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurar.
        /// </summary>
        internal static string restaurar {
            get {
                return ResourceManager.GetString("restaurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        internal static string rol {
            get {
                return ResourceManager.GetString("rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol:.
        /// </summary>
        internal static string rol2 {
            get {
                return ResourceManager.GetString("rol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        internal static string seguridad {
            get {
                return ResourceManager.GetString("seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitantes.
        /// </summary>
        internal static string solicitantes {
            get {
                return ResourceManager.GetString("solicitantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Respaldo.
        /// </summary>
        internal static string subir {
            get {
                return ResourceManager.GetString("subir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Equipo.
        /// </summary>
        internal static string tipoequipo {
            get {
                return ResourceManager.GetString("tipoequipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string usuarios {
            get {
                return ResourceManager.GetString("usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string usuarios2 {
            get {
                return ResourceManager.GetString("usuarios2", resourceCulture);
            }
        }
    }
}
