//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.site {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.site.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        internal static string acercade {
            get {
                return ResourceManager.GetString("acercade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  MEJORIAC es una solución web que nació en el año 2018 en el Information Access Center (IAC) Costa Rica con ayuda del programa World Friends ICT Volunteers 2018 (WFICTV), cuyo propósito es facilitar la gestión de los diferentes IAC en Centroamérica inicialmente, permitiendo la automatización estadística de uso de los diferentes espacios con que cuenta los IAC, y facilitando la presentación de reportes requeridos por National Information Society Agency (NIA).
        ///&lt;br/&gt;En el desarrollo de este proyecto participó e [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string acercade1 {
            get {
                return ResourceManager.GetString("acercade1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor complete todos lo campos para poder continuar.
        /// </summary>
        internal static string allTxt {
            get {
                return ResourceManager.GetString("allTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string bienvenido {
            get {
                return ResourceManager.GetString("bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        internal static string cerrarsesion {
            get {
                return ResourceManager.GetString("cerrarsesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        internal static string changePass {
            get {
                return ResourceManager.GetString("changePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haga click aquí para cambiar la contraseña.
        /// </summary>
        internal static string clickHere {
            get {
                return ResourceManager.GetString("clickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Nueva Contraseña.
        /// </summary>
        internal static string confirmNewPass {
            get {
                return ResourceManager.GetString("confirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IAC.
        /// </summary>
        internal static string iac {
            get {
                return ResourceManager.GetString("iac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento.
        /// </summary>
        internal static string mantenimiento {
            get {
                return ResourceManager.GetString("mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimado usuario, en este momento no posee acceso a este 
        ///modulo.
        ///Por favor diríjase al administrador del sistema, Gracias..
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        internal static string newPass {
            get {
                return ResourceManager.GetString("newPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string noMatch {
            get {
                return ResourceManager.GetString("noMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Anterior.
        /// </summary>
        internal static string oldPass {
            get {
                return ResourceManager.GetString("oldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña fue cambiada correctamente.
        /// </summary>
        internal static string passChanged {
            get {
                return ResourceManager.GetString("passChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Anterior Invalida.
        /// </summary>
        internal static string passInvalid {
            get {
                return ResourceManager.GetString("passInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no fue cambiada.
        /// </summary>
        internal static string passNoChanged {
            get {
                return ResourceManager.GetString("passNoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted se encuentra utilizando la contraseña dada por el administrador del sistema, por favor cambie la contraseña.
        /// </summary>
        internal static string passwordMessage {
            get {
                return ResourceManager.GetString("passwordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesos.
        /// </summary>
        internal static string procesos {
            get {
                return ResourceManager.GetString("procesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string reportes {
            get {
                return ResourceManager.GetString("reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        internal static string seguridad {
            get {
                return ResourceManager.GetString("seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero.
        /// </summary>
        internal static string tablero {
            get {
                return ResourceManager.GetString("tablero", resourceCulture);
            }
        }
    }
}
